[package]
name = "rust_lib_example"
version = "0.1.0"
authors = ["Tamae Honami <Tamae00Honami@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
